// Parcurge fluxul „Spune-mi problema ta” pe mobil (390px): validare, toți pașii, confirmare.
import { chromium } from "playwright";
const BASE = process.argv[2] ?? "http://localhost:3000";
const W = Number(process.env.W ?? 390);
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: W, height: 844 }, reducedMotion: "reduce" });
const shot = (n) => p.screenshot({ path: `qa/screenshots/problema-pas${n}-${W}.jpg`, fullPage: true, type: "jpeg", quality: 70 });
await p.goto(BASE + "/spune-mi-problema", { waitUntil: "networkidle" });
await p.getByRole("button", { name: /Continuă/ }).click();
const err1 = await p.locator(".error").first().textContent();
await shot("1-eroare");
await p.getByText("Iluminat", { exact: true }).click();
await p.getByRole("button", { name: /Continuă/ }).click();
await p.waitForTimeout(800);
await p.locator(".leaflet-container").click({ position: { x: 120, y: 140 } });
await p.getByLabel("Cartierul").selectOption("Berceni");
await shot("2");
await p.getByRole("button", { name: /Continuă/ }).click();
await p.getByLabel(/Descrie pe scurt/).fill("Stâlpul din fața blocului nu mai luminează.");
await shot("3");
await p.getByRole("button", { name: /Continuă/ }).click();
await p.getByRole("textbox", { name: "Telefon" }).fill("0712 345 678");
await p.getByRole("button", { name: /Trimite sesizarea/ }).click();
const err4 = await p.locator(".error").first().textContent();
await shot("4-eroare");
await p.getByRole("checkbox").check();
await p.getByRole("button", { name: /Trimite sesizarea/ }).click();
await p.getByText("Codul tău de referință").waitFor();
const cod = await p.locator(".font-mono").textContent();
await shot("5");
console.log({ err1, err4, cod, focus: await p.evaluate(() => document.activeElement?.textContent) });
await b.close();
